### ISSUE TITLE
this is a error

### ISSUE THREAD

**Issue by LooperzZ** [TruongKhang/TopicFM#14]
Traceback (most recent call last):
  File "D:\Project\image_match_code\TopicFM-main-n\demo\demo.py", line 112, in <module>
    matcher(batch)
  File "D:\software\anaconda\envs\pytorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Project\image_match_code\TopicFM-main-n\src\models\topic_fm.py", line 43, in forward
    feats_c, feats_f = self.backbone(torch.cat([data['image0'], data['image1']], dim=0))
  File "D:\software\anaconda\envs\pytorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Project\image_match_code\TopicFM-main-n\src\models\backbone\fpn.py", line 99, in forward
    x3_out = self.layer3_outconv2(x3_out+x4_out_2x)
RuntimeError: The size of tensor a (81) must match the size of tensor b (82) at non-singleton dimension 3

Process finished with exit code 1

**Comment by TruongKhang** [comment]
Hi @LooperzZ, which size of images did you use? The required image size is divisible by 16.

**Comment by LooperzZ** [comment]
okk,thank you.best wishes!
